# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luIg-meWE1FeMETRD5kc8ljv9iBSKBfL
"""

"""
Generate a JSON file (users_dataset_2500.json) with 2 500 users.

Differences vs. previous build
------------------------------
• Each vehicle’s rego_num is an *alphanumeric* string 1‑6 chars long
  (unique across the whole dataset, uppercase letters [A‑Z] and digits [0‑9]).
• Other requirements unchanged:
      – exactly one admin
      – each user has 1–3 vehicles
      – Licence_type is 'P', 'L', or 'Full'
      – phone numbers are 04xxxxxxxx (no spaces)
      – vehicle registration dates are ≥ 1 Mar 2024
"""

import json
import random
import string
from pathlib import Path
from faker import Faker

fake = Faker("en_AU")
Faker.seed(42)
random.seed(42)

INSURERS = [
    "Allianz", "NRMA", "AAMI", "Liberty",
    "Bingle", "Youi", "Suncorp", "QBE",
]

MAKES_MODELS = {
    "Toyota":      ["Corolla 2020", "Camry 2021", "Hilux 2019", "RAV4 2018"],
    "Ford":        ["Focus 2017", "Ranger 2020", "Mustang 2022"],
    "Mazda":       ["CX‑5 2020", "Mazda3 2019", "BT‑50 2021"],
    "Hyundai":     ["i30 2018", "Tucson 2020", "Kona 2021"],
    "Kia":         ["Cerato 2019", "Sportage 2021", "Seltos 2020"],
    "Nissan":      ["Navara 2018", "X‑Trail 2021", "Leaf 2020"],
    "Holden":      ["Commodore 2017", "Colorado 2019"],
    "Volkswagen":  ["Golf 2020", "Tiguan 2019", "Amarok 2021"],
}
VEHICLE_TYPES = ["sedan", "hatchback", "suv", "truck", "ute", "van"]

# ───────────────────────────────────────────────────────── helpers ──
def unique_license(issued: set[str]) -> str:
    while True:
        lic = "".join(random.choices(string.ascii_uppercase, k=2)) + \
              "".join(random.choices(string.digits, k=6))
        if lic not in issued:
            issued.add(lic)
            return lic

def username_from_name(name: str, issued: set[str]) -> str:
    base = "".join(name.lower().split())[:8]
    uname, n = base, 1
    while uname in issued:
        uname = f"{base}{n}"
        n += 1
    issued.add(uname)
    return uname

def random_phone() -> str:
    return "04" + "".join(random.choices(string.digits, k=8))

def unique_rego_string(issued: set[str]) -> str:
    """
    Return a unique alphanumeric rego string 1–6 chars (A‑Z 0‑9).
    Keeps shrinking probability of collision by allowing 1‑6 len.
    """
    chars = string.ascii_uppercase + string.digits
    while True:
        length = random.randint(4, 6)               # 4‑6 chars looks realistic
        rego = "".join(random.choices(chars, k=length))
        if rego not in issued:
            issued.add(rego)
            return rego

def random_vehicle(issued_regos: set[str]) -> tuple[str, dict]:
    make = random.choice(list(MAKES_MODELS))
    model = random.choice(MAKES_MODELS[make])
    rego_str = unique_rego_string(issued_regos)

    # ensure registration date ≥ 1 Mar 2024
    year = random.randint(2024, 2025)
    month = random.randint(3 if year == 2024 else 1, 12)
    day = random.randint(1, 28)
    reg_date = f"{day:02}/{month:02}/{year}"

    vehicle = {
        "make": make,
        "model": model,
        "registered_on": reg_date,
        "rego_num": rego_str,
        "type": random.choice(VEHICLE_TYPES),
    }
    return rego_str, vehicle

# ───────────────────────────────────────────────────── build users ──
def build_users(n_users: int = 2_500) -> dict:
    users = {}
    issued_usernames, issued_licenses, issued_regos = set(), set(), set()
    admin_index = random.randrange(n_users)       # single admin

    for idx in range(n_users):
        name = fake.name()
        user = {
            "License_type": random.choice(["P", "L", "Full"]),
            "address": fake.address().replace("\n", ", "),
            "admin": "yes" if idx == admin_index else "no",
            "email": fake.free_email(),
            "insurance": random.choice(INSURERS),
            "license": unique_license(issued_licenses),
            "name": name,
            "password": fake.password(length=10, special_chars=False),
            "phno": random_phone(),
            "username": username_from_name(name, issued_usernames),
        }

        # add 1–3 vehicles
        vehicles = {}
        for _ in range(random.randint(1, 3)):
            key, veh_obj = random_vehicle(issued_regos)
            vehicles[key] = veh_obj
        user["vehicles"] = vehicles

        users[user["license"]] = user

    return users

# ──────────────────────────────────────────────────────── run main ──
if __name__ == "__main__":
    data = build_users()
    out = Path("users_dataset_2500.json")
    out.write_text(json.dumps(data, indent=2))
    print(f"✅  Wrote {len(data):,} users → {out.resolve()}")

pip install faker

import json
from pathlib import Path

STATES = [
    "NSW", "VIC", "QLD", "SA", "WA", "TAS", "ACT", "NT"
]

LICENCE_TYPES = {
    "L": "Learner",       # speed cap ~80 km/h
    "P": "Provisional",   # speed cap ~100 km/h
    "Full": "Full"        # standard limits
}

ROAD_ZONES = {
    "Urban": 50,
    "Rural": 100,
    "Freeway": 110,
}

policies = []
counter = 1                  # for policy numbers


def add(text: str) -> None:
    """Append one policy (auto‑numbered)."""
    global counter
    policies.append({"policy_no": f"POL{counter:03}", "policytxt": text})
    counter += 1


# ---------------------------------------------------------------------
# 1. Speed‑limit policies (72)
# ---------------------------------------------------------------------
for state in STATES:
    for zone, full_speed in ROAD_ZONES.items():
        # Full licence
        add(f"In {state}, drivers holding a Full licence must not exceed "
            f"{full_speed} km/h on {zone.lower()} roads.")
        # Learner (L) – cap 30 km/h below zone limit but not above 80
        l_cap = min(full_speed - 30, 80)
        add(f"In {state}, Learner (L‑plate) drivers must not exceed "
            f"{l_cap} km/h on {zone.lower()} roads.")
        # Provisional (P) – cap 10 km/h below zone limit but not above 100
        p_cap = min(full_speed - 10, 100)
        add(f"In {state}, Provisional (P‑plate) drivers must not exceed "
            f"{p_cap} km/h on {zone.lower()} roads.")

# ---------------------------------------------------------------------
# 2. Freeway / heavy‑trailer bans for novice drivers (16)
# ---------------------------------------------------------------------
for state in STATES:
    add(f"Learner drivers are prohibited from driving on designated motorways "
        f"or freeways in {state}.")
    add(f"P‑plate drivers in {state} must not tow any trailer exceeding "
        "750 kg GVM (Gross Vehicle Mass).")

# ---------------------------------------------------------------------
# 3. Night‑driving curfews & passenger limits for P drivers (16)
# ---------------------------------------------------------------------
for state in STATES:
    add(f"In {state}, P‑plate drivers may not drive between 00:00 and 05:00 "
        "unless supervised by a Fully‑licensed driver.")
    add(f"P1 drivers in {state} are limited to ONE peer passenger (aged 16‑21) "
        "between 23:00 and 05:00.")

# ---------------------------------------------------------------------
# 4. Mobile‑phone ban for Learner & Provisional drivers (16)
# ---------------------------------------------------------------------
for state in STATES:
    add(f"In {state}, Learner and Provisional drivers must not use a mobile "
        "phone at all while the vehicle is moving or stationary (not parked).")

# ---------------------------------------------------------------------
# 5. School‑zone 40‑km/h universal rule (8)
# ---------------------------------------------------------------------
for state in STATES:
    add(f"All motorists in {state} must obey the 40 km/h limit in signed "
        "school zones on school days between 08:00‑09:30 and 14:30‑16:00.")

# ---------------------------------------------------------------------
# 6. Bus‑lane restriction for L & P drivers (8)
# ---------------------------------------------------------------------
for state in STATES:
    add(f"Learner and Provisional drivers in {state} may not use bus lanes "
        "during their posted operational hours.")

# ---------------------------------------------------------------------
# 7. Vehicle‑age inspection requirements (16)
# ---------------------------------------------------------------------
for state in STATES:
    add(f"Passenger vehicles in {state} that are more than 10 years old "
        "must pass an annual road‑worthiness inspection before registration "
        "renewal.")
    add(f"Passenger vehicles in {state} that are more than 15 years old "
        "must pass a six‑monthly road‑worthiness inspection.")

# ---------------------------------------------------------------------
# 8. EV road‑user charge (8)
# ---------------------------------------------------------------------
for state in STATES:
    add(f"From 1 July 2025, electric‑vehicle owners in {state} must report "
        "annual kilometres travelled and pay the state road‑user charge.")

# ---------------------------------------------------------------------
# 9. Declaration for owners with >2 vehicles (8)
# ---------------------------------------------------------------------
for state in STATES:
    add(f"Individuals registering more than TWO vehicles in {state} must "
        "declare their garage capacity and nominate a ‘primary residence’ "
        "for each vehicle.")

# ---------------------------------------------------------------------
# 10. Heavy‑vehicle fleet declaration (>3 vehicles over 4.5 t) (8)
# ---------------------------------------------------------------------
for state in STATES:
    add(f"Owners registering more than THREE heavy vehicles (GVM > 4.5 t) "
        f"in {state} must comply with Heavy Vehicle National Law accreditation.")

# ---------------------------------------------------------------------
# 11. Miscellaneous national updates (10)
# ---------------------------------------------------------------------
add("All drivers nationwide must carry a valid physical or digital licence "
    "while operating a motor vehicle.")
add("From 1 Jan 2026, child restraints must be used for passengers under "
    "145 cm or 12 years old, whichever comes first.")
add("Motorcycles manufactured after 1 Jan 2024 must meet Euro 5 emission "
    "standards to be registered.")
add("e‑Scooters capable of speeds above 25 km/h are classified as motor "
    "vehicles and require registration and CTP insurance.")
add("All vehicles sold after 1 July 2025 must provide a tyre‑pressure‑monitoring system (TPMS).")
add("From 2027, new passenger cars must feature Autonomous Emergency Braking (AEB) as standard.")
add("Diesel vehicles manufactured before 2005 are subject to an additional "
    "annual $100 environmental levy at registration renewal.")
add("Private sale of vehicles must include a Personal Property Securities "
    "Register (PPSR) certificate issued within the last 7 days.")
add("Shared‑car (car‑share) operators must provide third‑party property "
    "insurance of at least $20 million per collision.")
add("All vehicles fitted with aftermarket LED light bars must have them wired "
    "to operate only with high‑beam headlights.")

# ---------------------------------------------------------------------
# Write the dataset
# ---------------------------------------------------------------------
out_file = Path("policies_dataset.json")
with out_file.open("w", encoding="utf-8") as f:
    json.dump(policies, f, indent=2)

print(f"✅  Wrote {len(policies)} policies → {out_file.resolve()}")



